FROM node:5.11.1

# chromium in xvfb for browser tests
RUN apt-get update && \
  apt-get install -y \
  chromium \
  x11vnc \
  openbox \
  xvfb

# testem executable
RUN npm install -g testem

# Create Jenkins user
ARG UID
ARG GID
RUN groupadd jenkins -g $GID \
 && useradd -ms /bin/bash jenkins -u $UID -g $GID

# Prevent errors when running xvfb as jenkins user
RUN mkdir /tmp/.X11-unix \
 && chmod 1777 /tmp/.X11-unix \
 && chown root /tmp/.X11-unix

EXPOSE 5900
