import './content/home-background-int-test';
import './content/home-background-ui-test';
import './content/home-buttons-int-test';
import './content/home-buttons-ui-test';
import './content/home-favorites-int-test';
import './content/home-favorites-ui-test';
import './content/home-init-test';
import './content/home-mostvisited-int-test';
import './content/home-mostvisited-ui-test';
import './content/home-news-int-test';
import './content/home-news-ui-test';
// import './content/home-notification-int-test';
// import './content/home-notification-ui-test';
import './content/home-search-ui-test';
import './content/home-settings-int-test';
import './content/home-settings-ui-test';
