version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          # Systemjs is currently used only to provide mocking in our
          # unit-testing infrastructure. We are using a fairly old version
          # which would be pretty tricky to update. Also, the benefits of
          # updating are not clear at this point since the setup is working
          # well enough.
          #
          # If you feel adventurous, feel free to give this a shot though!
          #     => tests/runners/unit-node.js
          #
          # But you have been warned...
          dependency_name: "systemjs"
    default_reviewers:
      - "remusao"
      - "private-face"
      - "luciancor"
    default_labels:
      - "chore"
    automerged_updates:
      # Here we indicate to dependabot that whenever a dev dependency is
      # updated, and CI is green, and the version bump is withing version range
      # specified in package.json, then it should be safe to merge
      # automatically.
      - match:
          dependency_type: "development"
          update_type: "in_range"
