const base = require('./common/system');
const subprojects = require('./common/subprojects/bundles');
const publish = require('./common/publish');

const id = "android@cliqz.com";
const packageName = "cliqz";

module.exports = {
  "platform": "webextension",
  "brocfile": "Brocfile.webextension.js",
  "testsBasePath": "./build",
  "testem_launchers": ["unit-node", "Chrome"],
  "pack": "web-ext build -s build -a .",
  "sign": "python ./xpi-sign/xpisign.py -k $CLIQZ_CERT_PATH --signer openssl --passin file:$CLIQZ_CERT_PASS_PATH "+packageName+"-$PACKAGE_VERSION.zip "+packageName+"-$PACKAGE_VERSION-signed.zip && cp "+packageName+"-$PACKAGE_VERSION-signed.zip "+packageName+"-$PACKAGE_VERSION.zip",
  "publish": publish.toEdge(packageName, 'cliqz-android', 'zip'),
  "baseURL": "/modules/",
  "settings": {
    "id": id,
    "description": "",
    "name": "Cliqz",
    "antitrackingButton": false,
    "ATTRACK_TELEMETRY_PROVIDER": "platform",
    "channel": "MR00",
    "RESULTS_PROVIDER": "https://api.cliqz.com/api/v2/results?q=",
    "RICH_HEADER": "https://api.cliqz.com/api/v2/rich-header?path=/v2/map",
    "RESULTS_TIMEOUT": 3000,
    "CONFIG_PROVIDER": "https://api.cliqz.com/api/v1/config",
    "CDN_BASEURL": "https://cdn.cliqz.com",
    "ALLOWED_COUNTRY_CODES": ["de", "at", "ch", "es", "us", "fr", "nl", "gb", "it", "se"],
    "OFFERS_BE_BASE_URL": "https://offers-api.cliqz.com",
    "RICH_HEADER_PROXY_URL" : "hb-news.cliqz.com",
    "TRACKER_PROXY_PROXY_SIGNALING_DEFAULT": "wss://p2p-signaling-proxypeer.cliqz.com",
    "TRACKER_PROXY_PROXY_PEERS_DEFAULT": "https://p2p-signaling-proxypeer.cliqz.com/peers",
    "TRACKER_PROXY_PROXY_PEERS_EXIT_DEFAULT": "https://p2p-signaling-proxypeer.cliqz.com/exitNodes",
    "BW_URL": "https://antiphishing.cliqz.com/api/bwlist?md5=",
    "ANOLYSIS_BACKEND_URL": "https://anolysis.privacy.cliqz.com",
    "PRIVACY_SCORE_URL": "https://anti-tracking.cliqz.com/api/v1/score?",
    "SUPPORT_URL": "https://cliqz.com/support/",
    "TEAM_URL": "https://cliqz.com/team/",
    "HOMPAGE_URL": "https://cliqz.com/",
    "JOBS_URL": "https://cliqz.com/jobs/",
    "ENDPOINT_URL": "https://api.cliqz.com/api/v1/rich-header?path=/map&bmresult=",
    "CAMPAIGN_SERVER": "https://fec.cliqz.com/message/",
    "TRIQZ_URL": "https://cliqz.com/tips",
    "RESULTS_PROVIDER_LOG" : "https://api.cliqz.com/api/v1/logging?q=",
    "RESULTS_PROVIDER_PING": "https://api.cliqz.com/ping",
    "RESULTS_PROVIDER_ORDER": ["calculator", "history", "cliqz", "suggestions", "instant"],
    "CLEAR_RESULTS_AT_SESSION_START": false,
    "SAFE_BROWSING": "https://safe-browsing.cliqz.com",
    "UNINSTALL": "https://cliqz.com/home/offboarding",
    "FEEDBACK": "https://cliqz.com/feedback/",
    "BACKGROUND_IMAGE_URL": "https://cdn.cliqz.com/brands-database/database/",
    "CLIQZ_SAVE_URL": "https://cliqz.com/q=",
    "SUGGESTIONS_URL": "https://cliqz.com/search?q=",
    "ROTATED_TOP_NEWS": "rotated-top-news.cliqz.com",
    "HB_NEWS": "hb-news.cliqz.com",
    "TELEMETRY_ENDPOINT": "https://safebrowsing-experiment.cliqz.com",
    "INVENTORY_URL": "https://cdn.cliqz.com/browser-f/fun-demo/inventoryv2.txt.gz",
    "antitrackingPlaceholder": "cliqz.com/tracking",
    "antitrackingHeader": "CLIQZ-AntiTracking"
  },
  "modules": [
    "core",
    "static",
    "mobile-cards",
    "webextension-specific",
    "search",
    "anolysis",
    "geolocation"
  ],
  "bundles": [
    "mobile-cards/debug.bundle.js",
    "mobile-cards/cliqz-android.bundle.js",
    "webextension-specific/app.bundle.js",
  ],
  system: Object.assign({}, base.systemConfig, {
    map: Object.assign({}, base.systemConfig.map, {
      "@cliqz-oss/pouchdb": "node_modules/@cliqz-oss/pouchdb/dist/pouchdb.js",
      "@cliqz-oss/dexie": "node_modules/@cliqz-oss/dexie/dist/dexie.js",
      "mathjs": "node_modules/mathjs/dist/math.min.js",
      "react-native-view-shot": "modules/mobile-cards/external-libs/react-native-view-shot.js",
      "react-dom/unstable-native-dependencies": "node_modules/react-dom/unstable-native-dependencies.js",
      "ajv": "node_modules/ajv/dist/ajv.min.js",
    }),
    "packages": Object.assign({}, base.systemConfig.packages, {
      "is-obj": {
        "main": "./index.js"
      },
      "array-find-index": {
        "main": "./index.js"
      },
      "object-assign": {
        "main": "./index.js"
      },
      "react-native-web": {
        "map": {
          "./dist": "./dist/index.js",
          "./dist/apis/Animated": "./dist/apis/Animated/index.js",
          "./dist/apis/AppRegistry": "./dist/apis/AppRegistry/index.js",
          "./dist/apis/AppState": "./dist/apis/AppState/index.js",
          "./dist/apis/AsyncStorage": "./dist/apis/AsyncStorage/index.js",
          "./dist/apis/BackHandler": "./dist/apis/BackHandler/index.js",
          "./dist/apis/Clipboard": "./dist/apis/Clipboard/index.js",
          "./dist/apis/Dimensions": "./dist/apis/Dimensions/index.js",
          "./dist/apis/Easing": "./dist/apis/Easing/index.js",
          "./dist/apis/I18nManager": "./dist/apis/I18nManager/index.js",
          "./dist/apis/InteractionManager": "./dist/apis/InteractionManager/index.js",
          "./dist/apis/Keyboard": "./dist/apis/Keyboard/index.js",
          "./dist/apis/Linking": "./dist/apis/Linking/index.js",
          "./dist/apis/NetInfo": "./dist/apis/NetInfo/index.js",
          "./dist/apis/PanResponder": "./dist/apis/PanResponder/index.js",
          "./dist/apis/PixelRatio": "./dist/apis/PixelRatio/index.js",
          "./dist/apis/Platform": "./dist/apis/Platform/index.js",
          "./dist/apis/StyleSheet": "./dist/apis/StyleSheet/index.js",
          "./dist/apis/UIManager": "./dist/apis/UIManager/index.js",
          "./dist/apis/Vibration": "./dist/apis/Vibration/index.js",
          "./dist/components/ActivityIndicator": "./dist/components/ActivityIndicator/index.js",
          "./dist/components/Button": "./dist/components/Button/index.js",
          "./dist/components/Image": "./dist/components/Image/index.js",
          "./dist/components/FlatList": "./dist/components/FlatList/index.js",
          "./dist/components/ListView": "./dist/components/ListView/index.js",
          "./dist/components/KeyboardAvoidingView": "./dist/components/KeyboardAvoidingView/index.js",
          "./dist/components/Modal": "./dist/components/Modal/index.js",
          "./dist/components/Picker": "./dist/components/Picker/index.js",
          "./dist/components/ProgressBar": "./dist/components/ProgressBar/index.js",
          "./dist/components/RefreshControl": "./dist/components/RefreshControl/index.js",
          "./dist/components/SectionList": "./dist/components/SectionList/index.js",
          "./dist/components/ScrollView": "./dist/components/ScrollView/index.js",
          "./dist/components/Slider": "./dist/components/Slider/index.js",
          "./dist/components/StatusBar": "./dist/components/StatusBar/index.js",
          "./dist/components/StaticContainer": "./dist/components/StaticContainer/index.js",
          "./dist/components/StaticRenderer": "./dist/components/StaticRenderer/index.js",
          "./dist/components/Switch": "./dist/components/Switch/index.js",
          "./dist/components/Text": "./dist/components/Text/index.js",
          "./dist/components/TextInput": "./dist/components/TextInput/index.js",
          "./dist/components/UnimplementedView": "./dist/components/UnimplementedView/index.js",
          "./dist/components/View": "./dist/components/View/index.js",
          "./dist/components/VirtualizedList": "./dist/components/VirtualizedList/index.js",
          "./dist/modules/AccessibilityUtil": "./dist/modules/AccessibilityUtil/index.js",
          "./dist/modules/AssetRegistry": "./dist/modules/AssetRegistry/index.js",
          "./dist/modules/NativeMethodsMixin": "./dist/modules/NativeMethodsMixin/index.js",
          "./dist/modules/NativeModules": "./dist/modules/NativeModules/index.js",
          "./dist/modules/ReactNativePropRegistry": "./dist/modules/ReactNativePropRegistry/index.js",
          "./dist/modules/ScrollResponder": "./dist/modules/ScrollResponder/index.js",
          "./dist/modules/applyLayout": "./dist/modules/applyLayout/index.js",
          "./dist/modules/applyNativeMethods": "./dist/modules/applyNativeMethods/index.js",
          "./dist/modules/createDOMElement": "./dist/modules/createDOMElement/index.js",
          "./dist/modules/createDOMProps": "./dist/modules/createDOMProps/index.js",
          "./dist/modules/createElement": "./dist/modules/createElement/index.js",
          "./dist/modules/dismissKeyboard": "./dist/modules/dismissKeyboard/index.js",
          "./dist/modules/injectResponderEventPlugin": "./dist/modules/injectResponderEventPlugin/index.js",
          "./dist/modules/findNodeHandle": "./dist/modules/findNodeHandle/index.js",
          "./dist/modules/flattenStyle": "./dist/modules/flattenStyle/index.js",
          "./dist/modules/ImageLoader": "./dist/modules/ImageLoader/index.js",
          "./dist/modules/requestIdleCallback": "./dist/modules/requestIdleCallback/index.js",
          "./dist/modules/merge": "./dist/modules/merge/index.js",
          "./dist/modules/modality": "./dist/modules/modality/index.js",
          "./dist/modules/unitlessNumbers": "./dist/modules/unitlessNumbers/index.js",
          "./dist/modules/flattenArray": "./dist/modules/flattenArray/index.js",
          "./dist/modules/prefixStyles": "./dist/modules/prefixStyles/index.js",
          "./dist/modules/multiplyStyleLengthValue": "./dist/modules/multiplyStyleLengthValue/index.js",
          "./dist/modules/normalizeColor": "./dist/modules/normalizeColor/index.js",
          "./dist/modules/mapKeyValue": "./dist/modules/mapKeyValue/index.js",
          "./dist/modules/normalizeNativeEvent": "./dist/modules/normalizeNativeEvent/index.js",
          "./dist/modules/processColor": "./dist/modules/processColor/index.js",
          "./dist/vendor/setValueForStyles": "./dist/vendor/setValueForStyles/index.js",
          "./dist/vendor/warnValidStyle": "./dist/vendor/warnValidStyle/index.js",
          "./dist/vendor/PooledClass": "./dist/vendor/PooledClass/index.js",
          "./dist/vendor/dangerousStyleValue": "./dist/vendor/dangerousStyleValue/index.js",
          "./dist/vendor/hash": "./dist/vendor/hash/index.js",
          "./dist/vendor/TouchHistoryMath": "./dist/vendor/TouchHistoryMath/index.js"
        }
      }
    }),
  }),
  "subprojects": subprojects([
    'react',
    'reactDom',
    'rxjs',
    'mathjs',
  ]),
  builderDefault: base.builderConfig,
  "babelPlugins": [
    "react-native-web/babel"
  ]
}
