#!/usr/bin/env python

'''
    Updates clustering in extension
'''

import sys
import yaml
import json

with open("brands.yaml") as brand_file:
    output = json.dumps(yaml.load(brand_file), sys.stdout, indent=4)

with open("../cliqz@cliqz.com/chrome/content/cluster-rules-autogenerated.json", 'w') as out_file:
    out_file.write(output)

