/* global TESTS */

import adultQuestionTests from './tests/dropdown/adult-question';
import autocompletionAfterBackspaceTests from './tests/dropdown/autocompletion/after-backspace';
import autocompletionBackendTests from './tests/dropdown/autocompletion/backend';
import autocompletionBackendAndHistoryTests from './tests/dropdown/autocompletion/backend-and-history';
import autocompletionHappensOnceTests from './tests/dropdown/autocompletion/happens-once';
import autocompletionHistoryTests from './tests/dropdown/autocompletion/history';
import backspaceTests from './tests/dropdown/keyboard-navigation/backspace';
import bigMachineWithButtonsTests from './tests/dropdown/big-machine-with-buttons';
import bigMachineWithRichDataTests from './tests/dropdown/big-machine-rich-data';
import calculatorTests from './tests/dropdown/calculator';
import cinemaTests from './tests/dropdown/cinema';
import cleanUrlBarValueTests from './tests/dropdown/clean-url-bar-value';
import currencyConverterTests from './tests/dropdown/currency_converter';
import defaultSearchEngineTests from './tests/dropdown/default-search-engine';
import dialNumberTests from './tests/dropdown/dial-number';
import flightsTests from './tests/dropdown/flights-template';
import handlingUrlTests from './tests/dropdown/handling-url';
import historyAndNewsTests from './tests/dropdown/history-and-news';
import historyClusterTests from './tests/dropdown/history-cluster';
import historyDeletionTests from './tests/dropdown/keyboard-navigation/history-deletion';
import historyEnrichmentButtonsTests from './tests/dropdown/history-enrichment/buttons';
import historyEnrichmentCinemaTests from './tests/dropdown/history-enrichment/cinema';
import historyEnrichmentNewsStoryTests from './tests/dropdown/history-enrichment/news-story';
import historyEnrichmentNewsTests from './tests/dropdown/history-enrichment/news';
import historyEnrichmentLottoTests from './tests/dropdown/history-enrichment/lotto';
import historyEnrichmentRichDataTests from './tests/dropdown/history-enrichment/rich-data';
import historyEnrichmentVideosTests from './tests/dropdown/history-enrichment/videos';
import historyEnrichmentSoccerTests from './tests/dropdown/history-enrichment/soccer';
import keyboardNavigationAdultTests from './tests/dropdown/keyboard-navigation/adult-question';
import keyboardNavigationBmRichDataTests from './tests/dropdown/keyboard-navigation/bm-rich-data';
import keyboardNavigationBmWithButtonsTests from './tests/dropdown/keyboard-navigation/bm-with-buttons';
import keyboardNavigationCalculatorTypeTests from './tests/dropdown/keyboard-navigation/calculator-type';
import keyboardNavigationCurrencyConverterTests from './tests/dropdown/keyboard-navigation/currency-converter';
import keyboardNavigationFlightTypeTests from './tests/dropdown/keyboard-navigation/flight-type';
import keyboardNavigationLottoTypeTests from './tests/dropdown/keyboard-navigation/lotto-type';
import keyboardNavigationNewsTests from './tests/dropdown/keyboard-navigation/news';
import keyboardNavigationNewsStoryTests from './tests/dropdown/keyboard-navigation/news-story';
import keyboardNavigationSoccerGameTests from './tests/dropdown/keyboard-navigation/soccer-game';
import keyboardNavigationSoccerGroupTests from './tests/dropdown/keyboard-navigation/soccer-group';
import keyboardNavigationSimpleWithAutocompleteTests from './tests/dropdown/keyboard-navigation/simple-with-autocomplete';
import keyboardNavigationSimpleWithoutAutocompleteTests from './tests/dropdown/keyboard-navigation/simple-without-autocomplete';
import keyboardNavigationWeatherTests from './tests/dropdown/keyboard-navigation/weather';
import keyboardNavigationVideosTests from './tests/dropdown/keyboard-navigation/videos';
import localTests from './tests/dropdown/local';
import lotto6Aus49Tests from './tests/dropdown/lotto_6aus49';
import lottoEurojackpotTests from './tests/dropdown/lotto_eurojackpot';
import lottoGluecksspiraleTests from './tests/dropdown/lottogluecksspirale';
import lottoKenoTests from './tests/dropdown/lotto_keno';
import movieTests from './tests/dropdown/movie';
import movieShowtimesTests from './tests/dropdown/movie-showtimes';
import newsTests from './tests/dropdown/news';
import newsStoryTests from './tests/dropdown/news-story-of-the-day';
import offersNonOrganicV2Tests from './tests/dropdown/offers/non-organic-v2';
import offersNonOrganicStylesTests from './tests/dropdown/offers/non-organic-styles';
import simpleTests from './tests/dropdown/simple';
import soccerLigaGameTests from './tests/dropdown/soccer-liga-game';
import soccerLigaGroupTests from './tests/dropdown/soccer-liga-group';
import soccerLigaGroup2Tests from './tests/dropdown/soccer-liga-group2';
import soccerLigaTableTests from './tests/dropdown/soccer-liga-table';
import soccerLiveTickerTests from './tests/dropdown/soccer-live-ticker';
import suggestionsIntegrationTests from './tests/dropdown/suggestions-integration';
import telemetryEmptyQueryTests from './tests/dropdown/telemetry/empty-query';
import telemetryFullUrlTests from './tests/dropdown/telemetry/full-url';
import telemetryNoDropdownTests from './tests/dropdown/telemetry/no-dropdown';
import telemetrySearchEngineTests from './tests/dropdown/telemetry/search-engine';
import telemetrySearchWithTests from './tests/dropdown/telemetry/search-with';
import telemetryTwoSimpleWithAutocompleteTests from './tests/dropdown/telemetry/two-simple-with-autocomplete';
import telemetryTwoSimpleWithoutAutocompleteTests from './tests/dropdown/telemetry/two-simple-without-autocomplete';
import telemetryUrlbarTests from './tests/dropdown/telemetry/urlbar';
import timeTests from './tests/dropdown/time';
import unitConverterTests from './tests/dropdown/unit-converter';
import weatherTests from './tests/dropdown/weather';
import youtubeTests from './tests/dropdown/youtube';

TESTS.DropdownTests = function () {
  describe('dropdown', function () {
    describe('history enrichment', function () {
      historyEnrichmentButtonsTests();
      historyEnrichmentCinemaTests();
      historyEnrichmentNewsStoryTests();
      historyEnrichmentNewsTests();
      historyEnrichmentLottoTests();
      historyEnrichmentRichDataTests();
      historyEnrichmentVideosTests();
      historyEnrichmentSoccerTests();
    });
    describe('keyboard navigation', function () {
      keyboardNavigationAdultTests();
      keyboardNavigationBmRichDataTests();
      keyboardNavigationBmWithButtonsTests();
      keyboardNavigationCalculatorTypeTests();
      keyboardNavigationCurrencyConverterTests();
      keyboardNavigationFlightTypeTests();
      keyboardNavigationLottoTypeTests();
      keyboardNavigationNewsTests();
      keyboardNavigationNewsStoryTests();
      keyboardNavigationSoccerGameTests();
      keyboardNavigationSoccerGroupTests();
      keyboardNavigationSimpleWithAutocompleteTests();
      keyboardNavigationSimpleWithoutAutocompleteTests();
      keyboardNavigationVideosTests();
      keyboardNavigationWeatherTests();
    });
    adultQuestionTests();
    autocompletionAfterBackspaceTests();
    autocompletionBackendTests();
    autocompletionBackendAndHistoryTests();
    autocompletionHistoryTests();
    autocompletionHappensOnceTests();
    backspaceTests();
    bigMachineWithButtonsTests();
    bigMachineWithRichDataTests();
    calculatorTests();
    cinemaTests();
    cleanUrlBarValueTests();
    currencyConverterTests();
    defaultSearchEngineTests();
    dialNumberTests();
    flightsTests();
    handlingUrlTests();
    historyAndNewsTests();
    historyClusterTests();
    historyDeletionTests();
    localTests();
    lotto6Aus49Tests();
    lottoEurojackpotTests();
    lottoGluecksspiraleTests();
    lottoKenoTests();
    movieTests();
    movieShowtimesTests();
    newsTests();
    newsStoryTests();
    offersNonOrganicStylesTests();
    offersNonOrganicV2Tests();
    simpleTests();
    soccerLigaGameTests();
    soccerLigaGroupTests();
    soccerLigaGroup2Tests();
    soccerLigaTableTests();
    soccerLiveTickerTests();
    suggestionsIntegrationTests();
    telemetryEmptyQueryTests();
    telemetryFullUrlTests();
    telemetryNoDropdownTests();
    telemetrySearchEngineTests();
    telemetrySearchWithTests();
    telemetryTwoSimpleWithAutocompleteTests();
    telemetryTwoSimpleWithoutAutocompleteTests();
    telemetryUrlbarTests();
    timeTests();
    unitConverterTests();
    weatherTests();
    youtubeTests();
  });
};
